services:
  matrixa-sudby-ru:
    image: aristockij/ping-pong-image:latest
    container_name: ping-pong-image
    restart: always
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ping-pong-image

    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs:ro
    networks:
      - web

networks:
  web:
    driver: bridge
